services:
  - type: web
    name: video-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
